//! `mangrove fmt` — a deterministic, comment-preserving, meaning-preserving
//! formatter that walks the lossless CST and normalizes whitespace/indentation.

use mangrove_syntax::ParseError;
use mangrove_syntax::cst::{SyntaxKind as K, parse_cst};

pub struct FormatResult {
    pub text: String,
    pub errors: Vec<ParseError>,
}

/// Returns the inline separator to emit BEFORE `next`, given the previous
/// significant (non-trivia, non-newline) token kind `prev`.
/// Newlines and indentation are handled by the caller — this function only
/// decides inline spacing on a single logical line.
///
/// Callers handle the empty-vs-nonempty `{}`/`[]` inner-space rule by peeking
/// the next significant token and overriding R_BRACE/R_BRACKET spacing there.
fn space_between(prev: Option<K>, next: K) -> &'static str {
    use K::*;
    let Some(prev) = prev else { return "" };
    // no space before these tokens:
    if matches!(
        next,
        COLON | COMMA | R_PAREN | L_PAREN | QUESTION | DOT // R_BRACE / R_BRACKET handled by caller (empty-block peek)
    ) {
        return "";
    }
    // no space after these tokens (tight prefix).
    // L_BRACE and L_BRACKET are included here because the caller manually emits
    // the inner space for non-empty blocks — space_between must not double it.
    if matches!(
        prev,
        L_PAREN | L_BRACE | L_BRACKET | AT | DOT_DOT_DOT | BANG | DOT
    ) {
        return "";
    }
    // everything else gets a single space
    " "
}

/// Format `src`. Always returns formatted text; `errors` is non-empty if the
/// source had parse errors (the formatter still produces best-effort output,
/// since the CST is lossless even on error).
///
/// Normalizes inline spacing between tokens per the canonical rule-2 table.
/// Newlines and indentation are preserved verbatim (handled in Task 5).
/// WHITESPACE tokens are dropped and regenerated; NEWLINE / COMMENT / DOC /
/// DIRECTIVE pass through unchanged.
pub fn format_str(src: &str) -> FormatResult {
    use K::*;

    let parse = parse_cst(src);

    // Collect only leaf tokens in document order.
    let tokens: Vec<_> = parse
        .syntax()
        .descendants_with_tokens()
        .filter_map(|e| e.into_token())
        .collect();

    // Collect the kinds of significant (non-trivia, non-newline) tokens for
    // the empty-block peek: we need to look ahead past whitespace/newlines.
    // We'll do a two-pass approach: first build the significant-token index.
    //
    // Build a parallel vec: for each token index, the index of the next
    // significant token (skipping WHITESPACE, NEWLINE, COMMENT, DOC, DIRECTIVE).
    let is_significant = |k: K| !matches!(k, WHITESPACE | NEWLINE | COMMENT | DOC | DIRECTIVE);

    let n = tokens.len();
    // next_sig[i] = index of next significant token after i (or n if none)
    let mut next_sig = vec![n; n];
    let mut last = n;
    for i in (0..n).rev() {
        next_sig[i] = last;
        if is_significant(tokens[i].kind()) {
            last = i;
        }
    }

    let mut out = String::new();
    // The previous significant token kind (for space_between).
    let mut prev_sig: Option<K> = None;
    // After a NEWLINE we reset prev_sig so that the first token on a new line
    // gets no leading space from space_between (indentation is handled later).
    let mut after_newline = true;

    for (i, tok) in tokens.iter().enumerate() {
        let k = tok.kind();
        match k {
            WHITESPACE => {
                // Drop — regenerated by space_between logic.
            }
            NEWLINE => {
                out.push_str(tok.text());
                prev_sig = None;
                after_newline = true;
            }
            COMMENT | DOC | DIRECTIVE => {
                // Pass through; treat as non-significant for spacing purposes
                // (they appear after real tokens on a line, separated by at
                // least one space in the source — but we just output them
                // verbatim with the space already handled below via prev_sig).
                if !after_newline {
                    if let Some(p) = prev_sig {
                        out.push_str(space_between(Some(p), COMMENT));
                    }
                }
                out.push_str(tok.text());
                // Don't update prev_sig — comments are transparent to spacing.
            }
            R_BRACE | R_BRACKET => {
                // Decide inner space: if prev_sig is the matching opener and
                // the block is empty, no space; otherwise one space.
                // "Empty" means prev_sig is the matching L_BRACE / L_BRACKET.
                let empty = matches!(
                    (prev_sig, k),
                    (Some(L_BRACE), R_BRACE) | (Some(L_BRACKET), R_BRACKET)
                );
                if !after_newline && !empty && prev_sig.is_some() {
                    out.push(' ');
                }
                out.push_str(tok.text());
                prev_sig = Some(k);
                after_newline = false;
            }
            L_BRACE | L_BRACKET => {
                // Emit opener; then peek whether the next significant token
                // is the matching closer — if so, no inner space; else emit
                // a space after `{`/`[`.
                if !after_newline {
                    out.push_str(space_between(prev_sig, k));
                }
                out.push_str(tok.text());
                // Peek next significant token.
                let next_kind = if next_sig[i] < n {
                    Some(tokens[next_sig[i]].kind())
                } else {
                    None
                };
                let empty = matches!(
                    (k, next_kind),
                    (L_BRACE, Some(R_BRACE)) | (L_BRACKET, Some(R_BRACKET))
                );
                if !empty {
                    // Non-empty block: emit a space after opener.
                    // The closing space is handled in the R_BRACE/R_BRACKET arm.
                    // But only if the next significant token isn't on a new line.
                    // Check if next significant token follows on the same line
                    // (i.e., no NEWLINE between here and next_sig[i]).
                    let has_newline_before_next =
                        (i + 1..next_sig[i]).any(|j| tokens[j].kind() == NEWLINE);
                    if !has_newline_before_next {
                        out.push(' ');
                    }
                }
                prev_sig = Some(k);
                after_newline = false;
            }
            _ => {
                // Regular significant token.
                if !after_newline {
                    out.push_str(space_between(prev_sig, k));
                }
                out.push_str(tok.text());
                prev_sig = Some(k);
                after_newline = false;
            }
        }
    }

    FormatResult {
        text: out,
        errors: parse.errors,
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    fn assert_idempotent(src: &str) {
        let once = format_str(src).text;
        let twice = format_str(&once).text;
        assert_eq!(once, twice, "fmt must be idempotent for {src:?}");
    }

    /// Meaning preserved: for evaluable input the content hash is unchanged;
    /// for non-evaluable input the formatted source re-parses to the same
    /// non-trivia token sequence (structural equivalence).
    ///
    /// NOTE: trailing-comma cases (e.g. `[1,2,3,]`) must be EVALUABLE so they
    /// take the hash branch. Removing a trailing `,` would change the non-trivia
    /// token sequence, so such cases cannot use the structural branch.
    fn assert_meaning_preserved(src: &str) {
        let formatted = format_str(src).text;
        match (
            mangrove_syntax::parse(src),
            mangrove_syntax::parse(&formatted),
        ) {
            (Ok(a), Ok(b)) => assert_eq!(
                mangrove_canonical::hash(&a),
                mangrove_canonical::hash(&b),
                "hash changed by fmt for {src:?}"
            ),
            _ => {
                // non-evaluable: compare non-trivia token kinds+text of both CSTs
                let toks = |s: &str| {
                    mangrove_syntax::cst::parse_cst(s)
                        .syntax()
                        .descendants_with_tokens()
                        .filter_map(|e| e.into_token())
                        .filter(|t| {
                            !matches!(
                                t.kind(),
                                mangrove_syntax::cst::SyntaxKind::WHITESPACE
                                    | mangrove_syntax::cst::SyntaxKind::NEWLINE
                                    | mangrove_syntax::cst::SyntaxKind::COMMENT
                            )
                        })
                        .map(|t| (t.kind(), t.text().to_string()))
                        .collect::<Vec<_>>()
                };
                assert_eq!(
                    toks(src),
                    toks(&formatted),
                    "fmt changed non-trivia tokens for {src:?}"
                );
            }
        }
    }

    // Trailing-comma entry (`a: [1,2,3,]`) is kept EVALUABLE so it exercises
    // the hash branch — removing a `,` would change the non-trivia token set,
    // making the structural branch fail after Task 5.
    const CORPUS: &[&str] = &[
        "a: 1\n",
        "a: { b: 1, c: [ 2, 3 ] }\n",
        "type P = int & >= 1 & <= 65535\nschema P\nx: 5\n",
        "# lead\na: \"x\"  # trailing\n",
        "a: [1,2,3,]\n", // trailing comma — evaluable, so hash branch is used
    ];

    #[test]
    fn keeps_qualified_refs_tight() {
        assert_eq!(format_str("a: k.Deployment\n").text, "a: k.Deployment\n");
        assert_eq!(
            format_str("type T = k.Probe\nschema T\nx: 1\n").text,
            "type T = k.Probe\nschema T\nx: 1\n"
        );
    }

    #[test]
    fn normalizes_inline_spacing() {
        assert_eq!(format_str("a:1\n").text, "a: 1\n");
        assert_eq!(format_str("a : 1\n").text, "a: 1\n");
        assert_eq!(format_str("a: {b: 1,c: 2}\n").text, "a: { b: 1, c: 2 }\n");
        assert_eq!(format_str("xs: [1,2,3]\n").text, "xs: [ 1, 2, 3 ]\n");
        assert_eq!(
            format_str("type P=int&>=1&<=9\nschema P\nx: 1\n").text,
            "type P = int & >= 1 & <= 9\nschema P\nx: 1\n"
        );
        assert_eq!(format_str("e: {}\n").text, "e: {}\n"); // empty stays tight
    }

    #[test]
    fn oracles_hold_on_corpus() {
        for src in CORPUS {
            assert_idempotent(src);
            assert_meaning_preserved(src);
        }
    }

    /// Round-trip test for already-canonical inputs.
    ///
    /// The original "identity formatter" test checked that `format_str` reproduced
    /// source verbatim for all inputs. Now that the formatter normalizes inline
    /// spacing, that property only holds for inputs that are already canonically
    /// spaced. This test uses such inputs, ensuring a true idempotent round-trip.
    #[test]
    fn canonical_input_round_trips() {
        for src in [
            "a: 1\n",
            "a: { b: 1, c: [ 2, 3 ] }\n",
            "# comment\ntype T = int\nschema T\nx: 1\n",
            "",
        ] {
            assert_eq!(
                format_str(src).text,
                src,
                "canonical input must round-trip unchanged"
            );
        }
    }
}
